### ISSUE TITLE
_request usage

### ISSUE THREAD

**Issue by luiza-cicone** [mulesoft/js-client-oauth2#40]
Hello, 
First of all thanks for your module!

I have a question regarding the usage of `_request`. Why the underscore, is it for private module usage ?
Was it intended to be used like: `auth._request(token.sign(options));`
Or the request should be done directly using a request module like popsicle?

Also, is there a reason for `Querystring.stringify(options.body)` in the `_request` method? Popsicle already transforms the body based on the `Content-Type` header. And if another request handler is injected, it should do the same.
And why not leave popsicle handle the query params too?

Thanks

**Comment by blakeembrey** [comment]
It's for internal usage only, that's what the underscore usually means in JavaScript. It's not all left to Popsicle because there's a browser version that doesn't use popsicle. The request is better left to another module - it used to be provided here, but it just wasn't flexible enough to expose all the possible options from a request module like `popsicle` - so best to sign the request and make it directly with another library instead.
